version: '3.5'
services:
  nodejs-sample:
    build: .
    ports:
      - '8888:8888'
    depends_on:
      - db
      - consul
    networks:
      - app-network
    environment:
      - NODE_ENV=prod
  db:
    image: mongo:5.0.14
    ports:
      - '27018:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
    networks:
      - app-network
networks:
  app-network:
